global:
  scrape_interval: 5s
  evaluation_interval: 5s
  external_labels:
    cluster: sentinel-dev

scrape_configs:
  - job_name: demo-app
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['demo-app:8090']
        labels:
          service: demo-app
          role: customer-of-sentinel

  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
